--liquibase formatted sql

--changeset mcp-panel:002-teams dbms:postgresql
--comment: teams tablosu

-- =============================================================================
-- 1. Kimlik ve erişim
-- =============================================================================
-- Oturumlar Redis'te. Burada yalnızca kalıcı kimlik kayıtları var.

CREATE TABLE teams (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT teams_name_unique UNIQUE (name)
);

--rollback DROP TABLE IF EXISTS teams;
