--liquibase formatted sql

--changeset mcp-panel:004-user_invitations dbms:postgresql
--comment: user_invitations tablosu ve 1 indeksi

CREATE TABLE user_invitations (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email       text NOT NULL,
  role        user_role NOT NULL DEFAULT 'viewer',
  team_id     bigint REFERENCES teams(id) ON DELETE SET NULL,
  token_hash  text NOT NULL,
  invited_by  bigint REFERENCES users(id) ON DELETE SET NULL,
  expires_at  timestamptz NOT NULL,
  accepted_at timestamptz,
  created_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT user_invitations_token_unique UNIQUE (token_hash)
);

CREATE INDEX user_invitations_email_idx ON user_invitations (lower(email));

--rollback DROP TABLE IF EXISTS user_invitations;
