--liquibase formatted sql

--changeset mcp-panel:005-api_keys dbms:postgresql
--comment: api_keys tablosu ve 1 indeksi

CREATE TABLE api_keys (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         text NOT NULL,
  key_prefix   text NOT NULL,                  -- "mcp_live_9f3c" — listede gösterilir
  key_hash     text NOT NULL,                  -- tam anahtar yalnızca hash olarak
  created_by   bigint REFERENCES users(id) ON DELETE SET NULL,
  last_used_at timestamptz,
  revoked_at   timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT api_keys_hash_unique UNIQUE (key_hash)
);

CREATE INDEX api_keys_active_idx ON api_keys (revoked_at) WHERE revoked_at IS NULL;

--rollback DROP TABLE IF EXISTS api_keys;
