--liquibase formatted sql

--changeset mcp-panel:006-secrets dbms:postgresql
--comment: secrets tablosu

-- Sırlar şifreli saklanır; çözme uygulama tarafında KMS/vault ile yapılır.
CREATE TABLE secrets (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         text NOT NULL,
  kind         secret_kind NOT NULL DEFAULT 'other',
  ciphertext   bytea NOT NULL,                 -- ASLA düz metin
  key_id       text NOT NULL,                  -- şifrelemede kullanılan KMS anahtarı
  created_by   bigint REFERENCES users(id) ON DELETE SET NULL,
  last_used_at timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT secrets_name_unique UNIQUE (name)
);

--rollback DROP TABLE IF EXISTS secrets;
