--liquibase formatted sql

--changeset mcp-panel:007-ai_models dbms:postgresql
--comment: ai_models tablosu ve 2 indeksi

-- =============================================================================
-- 2. AI modelleri
-- =============================================================================

CREATE TABLE ai_models (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name              text NOT NULL,             -- "Claude Opus 5 — üretim"
  provider          model_provider NOT NULL DEFAULT 'anthropic',
  model_id          text NOT NULL,             -- "claude-opus-5"
  endpoint          text NOT NULL,             -- "https://api.anthropic.com"
  api_key_secret_id bigint REFERENCES secrets(id) ON DELETE RESTRICT,

  -- İstek parametreleri. Sağlayıcıya göre alanlar değiştiği için JSONB:
  --   anthropic → { "maxTokens": 16000, "effort": "high",
  --                 "thinking": "adaptive", "timeoutMs": 600000 }
  --   diğerleri → { "maxTokens": 4096, "temperature": 0.7, "timeoutMs": 120000 }
  params            jsonb NOT NULL DEFAULT '{}'::jsonb,

  -- Son bağlantı denemesinin sonucu:
  --   { "status": "online", "latencyMs": 820,
  --     "checkedAt": "2026-08-20T09:41:00Z", "error": null }
  health            jsonb NOT NULL DEFAULT '{}'::jsonb,

  enabled           boolean NOT NULL DEFAULT true,
  notes             text NOT NULL DEFAULT '',
  created_by        bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT ai_models_name_unique UNIQUE (name),
  CONSTRAINT ai_models_params_object CHECK (jsonb_typeof(params) = 'object'),
  CONSTRAINT ai_models_health_object CHECK (jsonb_typeof(health) = 'object'),
  -- Claude 4.6+ modellerinde temperature/top_p kaldırıldı; gönderilirse 400.
  -- Şema bunu JSONB üzerinde de zorlar.
  CONSTRAINT ai_models_no_temperature_on_anthropic
    CHECK (provider <> 'anthropic' OR NOT (params ? 'temperature'))
);

CREATE INDEX ai_models_enabled_idx ON ai_models (enabled);

-- Durum panelde filtrelenir; JSONB alanı üzerinden ifade indeksi yeterli.
CREATE INDEX ai_models_status_idx ON ai_models ((health ->> 'status'));

--rollback DROP TABLE IF EXISTS ai_models;
