--liquibase formatted sql

--changeset mcp-panel:008-host_groups dbms:postgresql
--comment: host_groups tablosu ve 1 indeksi

-- =============================================================================
-- 3. Sunucu envanteri
-- =============================================================================
-- Grup, adres listesinden ibaret. Ayrı `hosts` + `host_group_members`
-- tablolarına gerek yok; liste sahibiyle birlikte okunup yazılıyor.

CREATE TABLE host_groups (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL,
  description text NOT NULL DEFAULT '',
  -- ["web-01.internal", "web-02.internal", …]
  hosts       jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT host_groups_name_unique UNIQUE (name),
  CONSTRAINT host_groups_hosts_array CHECK (jsonb_typeof(hosts) = 'array')
);

-- "Bu adres hangi gruplarda?" sorusu için.
CREATE INDEX host_groups_hosts_idx ON host_groups USING gin (hosts);

--rollback DROP TABLE IF EXISTS host_groups;
