--liquibase formatted sql

--changeset mcp-panel:010-actions dbms:postgresql
--comment: actions tablosu ve 3 indeksi

-- Aksiyonlar ayrı tablo kalıyor: sıralanır, tek tek silinir/eklenir ve
-- `runs` buradan bir satıra işaret eder. Tipe özgü ayarlar `config` içinde.
CREATE TABLE actions (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  definition_id bigint NOT NULL REFERENCES definitions(id) ON DELETE CASCADE,
  kind          action_kind NOT NULL,
  name          text NOT NULL,
  description   text NOT NULL DEFAULT '',
  position      integer NOT NULL DEFAULT 0,

  -- Tipe göre değişen tüm ayarlar. Şekli DATABASE.md'de.
  --   rest → method, url, headers[], body, timeoutMs
  --   ssh  → targetMode, host, hosts[], strategy, auth, commandMode, command,
  --          allowedCommands[], blockedPatterns[], sudo …
  --   db   → engine, host, port, database, queryMode, query, schemaHint,
  --          allowedOperations[], maxRows, readOnly …
  config        jsonb NOT NULL DEFAULT '{}'::jsonb,

  -- Grup hedefi JSONB'de değil gerçek kolonda: silme davranışı ve
  -- "bu grubu kim kullanıyor" sorgusu buna bağlı.
  host_group_id bigint REFERENCES host_groups(id) ON DELETE SET NULL,

  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT actions_config_object CHECK (jsonb_typeof(config) = 'object'),
  -- Grup hedefi yalnızca SSH aksiyonunda anlamlı
  CONSTRAINT actions_group_only_ssh
    CHECK (host_group_id IS NULL OR kind = 'ssh')
);

CREATE INDEX actions_definition_idx ON actions (definition_id, position);

CREATE INDEX actions_group_idx ON actions (host_group_id);

-- config içinde sır kimliği / yasak kalıp araması için.
CREATE INDEX actions_config_idx ON actions USING gin (config);

--rollback DROP TABLE IF EXISTS actions;
