--liquibase formatted sql

--changeset mcp-panel:011-runs dbms:postgresql
--comment: runs tablosu ve 2 indeksi

-- =============================================================================
-- 5. Çalıştırma ve denetim
-- =============================================================================

CREATE TABLE runs (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  definition_id bigint NOT NULL REFERENCES definitions(id) ON DELETE CASCADE,
  action_id     bigint REFERENCES actions(id) ON DELETE SET NULL,
  actor_id      bigint REFERENCES users(id) ON DELETE SET NULL,
  actor_label   text,                          -- "agent:ci-bot" gibi insan olmayan çağıranlar
  status        run_status NOT NULL DEFAULT 'pending',

  -- Çalıştırmaya geçilen girdi değerleri. Sır tipindekiler null bırakılır:
  --   { "surum": "v2.4.0", "ortam": "production", "deploy_token": null }
  inputs        jsonb NOT NULL DEFAULT '{}'::jsonb,

  -- Dinamik modda modelin ürettiği metin — denetim için saklanır.
  generated_command text,
  generated_query   text,
  approved_by   bigint REFERENCES users(id) ON DELETE SET NULL,
  approved_at   timestamptz,

  started_at    timestamptz,
  finished_at   timestamptz,
  error         text,
  created_at    timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT runs_inputs_object CHECK (jsonb_typeof(inputs) = 'object')
);

CREATE INDEX runs_definition_idx ON runs (definition_id, created_at DESC);

CREATE INDEX runs_status_idx ON runs (status)
  WHERE status IN ('pending', 'running', 'awaiting_approval');

--rollback DROP TABLE IF EXISTS runs;
