--liquibase formatted sql

--changeset mcp-panel:012-run_targets dbms:postgresql
--comment: run_targets tablosu ve 1 indeksi

-- Tablo kalıyor: 10 sunuculuk bir turda her hedef kendi hızında ilerler ve
-- satırı tek tek güncellenir. JSONB dizisinde bunu yapmak kilit ve yazma
-- çakışması demek olurdu.
CREATE TABLE run_targets (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id         bigint NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
  address        text NOT NULL,
  batch_index    integer NOT NULL DEFAULT 0,   -- rolling stratejide kaçıncı tur
  status         target_status NOT NULL DEFAULT 'pending',
  exit_code      integer,
  duration_ms    integer,
  stdout_excerpt text,
  stderr_excerpt text,
  started_at     timestamptz,
  finished_at    timestamptz,
  CONSTRAINT run_targets_unique UNIQUE (run_id, address)
);

CREATE INDEX run_targets_run_idx ON run_targets (run_id, batch_index);

--rollback DROP TABLE IF EXISTS run_targets;
