--liquibase formatted sql

--changeset mcp-panel:013-tool_calls dbms:postgresql
--comment: tool_calls tablosu ve 4 indeksi

-- Araç çağrısı kayıtları — panelde /logs sayfasını besler
CREATE TABLE tool_calls (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  definition_id bigint REFERENCES definitions(id) ON DELETE SET NULL,
  tool_name     text NOT NULL,                 -- tanım silinse de kayıt okunabilsin
  model_id      bigint REFERENCES ai_models(id) ON DELETE SET NULL,
  model_label   text NOT NULL DEFAULT '',      -- "claude-opus-5"
  actor_id      bigint REFERENCES users(id) ON DELETE SET NULL,
  actor_label   text NOT NULL,
  run_id        bigint REFERENCES runs(id) ON DELETE SET NULL,
  level         log_level NOT NULL DEFAULT 'info',
  duration_ms   integer NOT NULL DEFAULT 0,
  input_tokens  integer,
  output_tokens integer,
  message       text NOT NULL DEFAULT '',
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX tool_calls_recent_idx ON tool_calls (created_at DESC);

CREATE INDEX tool_calls_definition_idx ON tool_calls (definition_id, created_at DESC);

CREATE INDEX tool_calls_model_idx ON tool_calls (model_id, created_at DESC);

CREATE INDEX tool_calls_level_idx ON tool_calls (level, created_at DESC);

--rollback DROP TABLE IF EXISTS tool_calls;
