--liquibase formatted sql

--changeset mcp-panel:014-audit_events dbms:postgresql
--comment: audit_events tablosu ve 2 indeksi

-- Genel denetim izi — panelde "Son hareketler" akışını besler
CREATE TABLE audit_events (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id    bigint REFERENCES users(id) ON DELETE SET NULL,
  actor_label text NOT NULL,
  action      text NOT NULL,                   -- "definition.created"
  entity_type text NOT NULL,                   -- "definition"
  entity_id   bigint,
  metadata    jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX audit_events_recent_idx ON audit_events (created_at DESC);

CREATE INDEX audit_events_entity_idx ON audit_events (entity_type, entity_id);

--rollback DROP TABLE IF EXISTS audit_events;
