--liquibase formatted sql

--changeset mcp-panel:018-conversations dbms:postgresql
--comment: konsol sohbet geçmişi

-- Konsol turları yalnızca tarayıcının belleğinde duruyordu: sayfadan çıkan kullanıcı
-- sorduğu cümleyi, modelin hangi aracı niçin seçtiğini ve ürettiği planı birlikte
-- kaybediyordu. Yürütülen işler zaten runs tablosunda; kaybolan şey sohbetin kendisi
-- ve kutu işaretsizken yapılan denemeler, ki onlar hiç run kaydı oluşturmuyor.
CREATE TABLE conversations (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_ref text NOT NULL,
  owner_id         bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title            text NOT NULL DEFAULT '',
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT conversations_ref_unique UNIQUE (conversation_ref)
);

-- Bir sohbet sahibine aittir; sorulan cümleler iş bilgisi taşır ve varsayılan olarak
-- paylaşılmaz. Liste her zaman "benim sohbetlerim, en yenisi üstte" diye okunduğu için
-- indeks de o sırayı taşır.
CREATE INDEX conversations_owner_idx ON conversations (owner_id, updated_at DESC);

CREATE TABLE conversation_turns (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id bigint NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  prompt          text NOT NULL,
  -- Operatörün sabitlediği araç; boşsa seçimi model yapmıştır. Modelin seçtiği araç
  -- tool_name'de durur — ikisi ayrı sorular, o yüzden ayrı kolonlar.
  pinned_tool     text,
  tool_name       text,
  executed        boolean NOT NULL DEFAULT false,
  status          text,
  reasoning       text,
  problem         text,
  statement       text,
  -- Çıktının kopyası değil, işaretçisi. Tek kopya olsun diye: iki kopya demek,
  -- silinmesi gereken kişisel veriyi iki yerde aramak demek. Bir tur tek bir iş
  -- kuyruğa verir (dispatch.run_id), o yüzden tekil.
  run_ref         text,
  failure         text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX conversation_turns_conversation_idx ON conversation_turns (conversation_id, id);

--rollback DROP TABLE IF EXISTS conversation_turns;
--rollback DROP TABLE IF EXISTS conversations;
