--
-- PostgreSQL database dump
--

\restrict rgjCT1JWfV2zMw4aCrJeMWMKpKsPQFXq4055DpFQeOxlw7TXkOPu624cXh35gBu

-- Dumped from database version 17.7
-- Dumped by pg_dump version 17.7

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: action_kind; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.action_kind AS ENUM (
    'rest',
    'ssh',
    'db'
);


--
-- Name: log_level; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.log_level AS ENUM (
    'info',
    'warn',
    'error'
);


--
-- Name: model_provider; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.model_provider AS ENUM (
    'anthropic',
    'openai_compatible',
    'azure',
    'vertex',
    'bedrock',
    'ollama',
    'custom'
);


--
-- Name: model_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.model_status AS ENUM (
    'online',
    'degraded',
    'offline',
    'unchecked'
);


--
-- Name: run_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.run_status AS ENUM (
    'pending',
    'awaiting_approval',
    'running',
    'succeeded',
    'failed',
    'cancelled'
);


--
-- Name: secret_kind; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.secret_kind AS ENUM (
    'ssh_private_key',
    'ssh_passphrase',
    'password',
    'api_token',
    'model_api_key',
    'other'
);


--
-- Name: target_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.target_status AS ENUM (
    'pending',
    'running',
    'succeeded',
    'failed',
    'skipped'
);


--
-- Name: user_role; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.user_role AS ENUM (
    'admin',
    'developer',
    'viewer'
);


--
-- Name: user_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.user_status AS ENUM (
    'active',
    'invited',
    'suspended'
);


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: actions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.actions (
    id bigint NOT NULL,
    definition_id bigint NOT NULL,
    kind public.action_kind NOT NULL,
    name text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    "position" integer DEFAULT 0 NOT NULL,
    config jsonb DEFAULT '{}'::jsonb NOT NULL,
    host_group_id bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT actions_config_object CHECK ((jsonb_typeof(config) = 'object'::text)),
    CONSTRAINT actions_group_only_ssh CHECK (((host_group_id IS NULL) OR (kind = 'ssh'::public.action_kind)))
);


--
-- Name: actions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.actions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.actions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ai_models; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_models (
    id bigint NOT NULL,
    name text NOT NULL,
    provider public.model_provider DEFAULT 'anthropic'::public.model_provider NOT NULL,
    model_id text NOT NULL,
    endpoint text NOT NULL,
    api_key_secret_id bigint,
    params jsonb DEFAULT '{}'::jsonb NOT NULL,
    health jsonb DEFAULT '{}'::jsonb NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    notes text DEFAULT ''::text NOT NULL,
    created_by bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ai_models_health_object CHECK ((jsonb_typeof(health) = 'object'::text)),
    CONSTRAINT ai_models_no_temperature_on_anthropic CHECK (((provider <> 'anthropic'::public.model_provider) OR (NOT (params ? 'temperature'::text)))),
    CONSTRAINT ai_models_params_object CHECK ((jsonb_typeof(params) = 'object'::text))
);


--
-- Name: ai_models_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ai_models ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_models_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_keys; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.api_keys (
    id bigint NOT NULL,
    name text NOT NULL,
    key_prefix text NOT NULL,
    key_hash text NOT NULL,
    created_by bigint,
    last_used_at timestamp with time zone,
    revoked_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: api_keys_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.api_keys ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_keys_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_events (
    id bigint NOT NULL,
    actor_id bigint,
    actor_label text NOT NULL,
    action text NOT NULL,
    entity_type text NOT NULL,
    entity_id bigint,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: audit_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.audit_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: conversation_turns; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.conversation_turns (
    id bigint NOT NULL,
    conversation_id bigint NOT NULL,
    prompt text NOT NULL,
    pinned_tool text,
    tool_name text,
    executed boolean DEFAULT false NOT NULL,
    status text,
    reasoning text,
    problem text,
    statement text,
    run_ref text,
    failure text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    answer text,
    warnings jsonb,
    goal_turn_id bigint,
    deferred jsonb,
    arguments jsonb,
    action_id bigint
);


--
-- Name: conversation_turns_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.conversation_turns ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conversation_turns_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: conversations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.conversations (
    id bigint NOT NULL,
    conversation_ref text NOT NULL,
    owner_id bigint NOT NULL,
    title text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    summary text,
    summarised_through_id bigint
);


--
-- Name: conversations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.conversations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conversations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: definitions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.definitions (
    id bigint NOT NULL,
    name text NOT NULL,
    tool_name text NOT NULL,
    tool_description text DEFAULT ''::text NOT NULL,
    model_id bigint,
    system_prompt text DEFAULT ''::text NOT NULL,
    inputs jsonb DEFAULT '[]'::jsonb NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    created_by bigint,
    updated_by bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT definitions_inputs_array CHECK ((jsonb_typeof(inputs) = 'array'::text)),
    CONSTRAINT definitions_tool_name_format CHECK ((tool_name ~ '^[a-z_][a-z0-9_]*$'::text))
);


--
-- Name: definitions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.definitions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.definitions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: host_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.host_groups (
    id bigint NOT NULL,
    name text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    hosts jsonb DEFAULT '[]'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT host_groups_hosts_array CHECK ((jsonb_typeof(hosts) = 'array'::text))
);


--
-- Name: host_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.host_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.host_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: run_targets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.run_targets (
    id bigint NOT NULL,
    run_id bigint NOT NULL,
    address text NOT NULL,
    batch_index integer DEFAULT 0 NOT NULL,
    status public.target_status DEFAULT 'pending'::public.target_status NOT NULL,
    exit_code integer,
    duration_ms integer,
    stdout_excerpt text,
    stderr_excerpt text,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    result_rows jsonb,
    output_sealed bytea,
    output_key_id text
);


--
-- Name: run_targets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.run_targets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.run_targets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: runs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.runs (
    id bigint NOT NULL,
    definition_id bigint NOT NULL,
    action_id bigint,
    actor_id bigint,
    actor_label text,
    status public.run_status DEFAULT 'pending'::public.run_status NOT NULL,
    inputs jsonb DEFAULT '{}'::jsonb NOT NULL,
    generated_command text,
    generated_query text,
    approved_by bigint,
    approved_at timestamp with time zone,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    error text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    run_ref text,
    action_ref text,
    purpose text DEFAULT 'execute'::text NOT NULL,
    CONSTRAINT runs_inputs_object CHECK ((jsonb_typeof(inputs) = 'object'::text))
);


--
-- Name: runs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.runs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.runs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: secrets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.secrets (
    id bigint NOT NULL,
    name text NOT NULL,
    kind public.secret_kind DEFAULT 'other'::public.secret_kind NOT NULL,
    ciphertext bytea NOT NULL,
    key_id text NOT NULL,
    created_by bigint,
    last_used_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: secrets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.secrets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.secrets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: teams; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.teams (
    id bigint NOT NULL,
    name text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: teams_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.teams ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teams_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tool_calls; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tool_calls (
    id bigint NOT NULL,
    definition_id bigint,
    tool_name text NOT NULL,
    model_id bigint,
    model_label text DEFAULT ''::text NOT NULL,
    actor_id bigint,
    actor_label text NOT NULL,
    run_id bigint,
    level public.log_level DEFAULT 'info'::public.log_level NOT NULL,
    duration_ms integer DEFAULT 0 NOT NULL,
    input_tokens integer,
    output_tokens integer,
    message text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: tool_calls_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tool_calls ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tool_calls_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_invitations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_invitations (
    id bigint NOT NULL,
    email text NOT NULL,
    role public.user_role DEFAULT 'viewer'::public.user_role NOT NULL,
    team_id bigint,
    token_hash text NOT NULL,
    invited_by bigint,
    expires_at timestamp with time zone NOT NULL,
    accepted_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: user_invitations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_invitations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_invitations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email text NOT NULL,
    full_name text NOT NULL,
    password_hash text,
    role public.user_role DEFAULT 'viewer'::public.user_role NOT NULL,
    status public.user_status DEFAULT 'invited'::public.user_status NOT NULL,
    team_id bigint,
    avatar_url text,
    preferences jsonb DEFAULT '{}'::jsonb NOT NULL,
    last_login_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: actions actions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.actions
    ADD CONSTRAINT actions_pkey PRIMARY KEY (id);


--
-- Name: ai_models ai_models_name_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_models
    ADD CONSTRAINT ai_models_name_unique UNIQUE (name);


--
-- Name: ai_models ai_models_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_models
    ADD CONSTRAINT ai_models_pkey PRIMARY KEY (id);


--
-- Name: api_keys api_keys_hash_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_keys
    ADD CONSTRAINT api_keys_hash_unique UNIQUE (key_hash);


--
-- Name: api_keys api_keys_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_keys
    ADD CONSTRAINT api_keys_pkey PRIMARY KEY (id);


--
-- Name: audit_events audit_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_events
    ADD CONSTRAINT audit_events_pkey PRIMARY KEY (id);


--
-- Name: conversation_turns conversation_turns_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversation_turns
    ADD CONSTRAINT conversation_turns_pkey PRIMARY KEY (id);


--
-- Name: conversations conversations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT conversations_pkey PRIMARY KEY (id);


--
-- Name: conversations conversations_ref_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT conversations_ref_unique UNIQUE (conversation_ref);


--
-- Name: definitions definitions_name_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.definitions
    ADD CONSTRAINT definitions_name_unique UNIQUE (name);


--
-- Name: definitions definitions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.definitions
    ADD CONSTRAINT definitions_pkey PRIMARY KEY (id);


--
-- Name: definitions definitions_tool_name_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.definitions
    ADD CONSTRAINT definitions_tool_name_unique UNIQUE (tool_name);


--
-- Name: host_groups host_groups_name_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.host_groups
    ADD CONSTRAINT host_groups_name_unique UNIQUE (name);


--
-- Name: host_groups host_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.host_groups
    ADD CONSTRAINT host_groups_pkey PRIMARY KEY (id);


--
-- Name: run_targets run_targets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.run_targets
    ADD CONSTRAINT run_targets_pkey PRIMARY KEY (id);


--
-- Name: run_targets run_targets_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.run_targets
    ADD CONSTRAINT run_targets_unique UNIQUE (run_id, address);


--
-- Name: runs runs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.runs
    ADD CONSTRAINT runs_pkey PRIMARY KEY (id);


--
-- Name: secrets secrets_name_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.secrets
    ADD CONSTRAINT secrets_name_unique UNIQUE (name);


--
-- Name: secrets secrets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.secrets
    ADD CONSTRAINT secrets_pkey PRIMARY KEY (id);


--
-- Name: teams teams_name_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT teams_name_unique UNIQUE (name);


--
-- Name: teams teams_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT teams_pkey PRIMARY KEY (id);


--
-- Name: tool_calls tool_calls_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_calls
    ADD CONSTRAINT tool_calls_pkey PRIMARY KEY (id);


--
-- Name: user_invitations user_invitations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_invitations
    ADD CONSTRAINT user_invitations_pkey PRIMARY KEY (id);


--
-- Name: user_invitations user_invitations_token_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_invitations
    ADD CONSTRAINT user_invitations_token_unique UNIQUE (token_hash);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: actions_config_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX actions_config_idx ON public.actions USING gin (config);


--
-- Name: actions_definition_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX actions_definition_idx ON public.actions USING btree (definition_id, "position");


--
-- Name: actions_group_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX actions_group_idx ON public.actions USING btree (host_group_id);


--
-- Name: ai_models_enabled_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ai_models_enabled_idx ON public.ai_models USING btree (enabled);


--
-- Name: ai_models_status_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ai_models_status_idx ON public.ai_models USING btree (((health ->> 'status'::text)));


--
-- Name: api_keys_active_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX api_keys_active_idx ON public.api_keys USING btree (revoked_at) WHERE (revoked_at IS NULL);


--
-- Name: audit_events_entity_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audit_events_entity_idx ON public.audit_events USING btree (entity_type, entity_id);


--
-- Name: audit_events_recent_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audit_events_recent_idx ON public.audit_events USING btree (created_at DESC);


--
-- Name: conversation_turns_conversation_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX conversation_turns_conversation_idx ON public.conversation_turns USING btree (conversation_id, id);


--
-- Name: conversation_turns_goal_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX conversation_turns_goal_idx ON public.conversation_turns USING btree (goal_turn_id) WHERE (goal_turn_id IS NOT NULL);


--
-- Name: conversations_owner_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX conversations_owner_idx ON public.conversations USING btree (owner_id, updated_at DESC);


--
-- Name: definitions_enabled_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX definitions_enabled_idx ON public.definitions USING btree (enabled);


--
-- Name: definitions_model_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX definitions_model_idx ON public.definitions USING btree (model_id);


--
-- Name: host_groups_hosts_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX host_groups_hosts_idx ON public.host_groups USING gin (hosts);


--
-- Name: run_targets_run_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX run_targets_run_idx ON public.run_targets USING btree (run_id, batch_index);


--
-- Name: runs_action_ref_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX runs_action_ref_unique ON public.runs USING btree (action_ref) WHERE (action_ref IS NOT NULL);


--
-- Name: runs_definition_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX runs_definition_idx ON public.runs USING btree (definition_id, created_at DESC);


--
-- Name: runs_run_ref_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX runs_run_ref_idx ON public.runs USING btree (run_ref) WHERE (run_ref IS NOT NULL);


--
-- Name: runs_status_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX runs_status_idx ON public.runs USING btree (status) WHERE (status = ANY (ARRAY['pending'::public.run_status, 'running'::public.run_status, 'awaiting_approval'::public.run_status]));


--
-- Name: tool_calls_definition_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tool_calls_definition_idx ON public.tool_calls USING btree (definition_id, created_at DESC);


--
-- Name: tool_calls_level_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tool_calls_level_idx ON public.tool_calls USING btree (level, created_at DESC);


--
-- Name: tool_calls_model_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tool_calls_model_idx ON public.tool_calls USING btree (model_id, created_at DESC);


--
-- Name: tool_calls_recent_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tool_calls_recent_idx ON public.tool_calls USING btree (created_at DESC);


--
-- Name: user_invitations_email_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_invitations_email_idx ON public.user_invitations USING btree (lower(email));


--
-- Name: users_email_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX users_email_unique ON public.users USING btree (lower(email));


--
-- Name: users_team_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_team_idx ON public.users USING btree (team_id);


--
-- Name: actions actions_definition_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.actions
    ADD CONSTRAINT actions_definition_id_fkey FOREIGN KEY (definition_id) REFERENCES public.definitions(id) ON DELETE CASCADE;


--
-- Name: actions actions_host_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.actions
    ADD CONSTRAINT actions_host_group_id_fkey FOREIGN KEY (host_group_id) REFERENCES public.host_groups(id) ON DELETE SET NULL;


--
-- Name: ai_models ai_models_api_key_secret_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_models
    ADD CONSTRAINT ai_models_api_key_secret_id_fkey FOREIGN KEY (api_key_secret_id) REFERENCES public.secrets(id) ON DELETE RESTRICT;


--
-- Name: ai_models ai_models_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_models
    ADD CONSTRAINT ai_models_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: api_keys api_keys_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_keys
    ADD CONSTRAINT api_keys_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: audit_events audit_events_actor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_events
    ADD CONSTRAINT audit_events_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: conversation_turns conversation_turns_conversation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversation_turns
    ADD CONSTRAINT conversation_turns_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id) ON DELETE CASCADE;


--
-- Name: conversation_turns conversation_turns_goal_turn_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversation_turns
    ADD CONSTRAINT conversation_turns_goal_turn_id_fkey FOREIGN KEY (goal_turn_id) REFERENCES public.conversation_turns(id) ON DELETE CASCADE;


--
-- Name: conversations conversations_owner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT conversations_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: definitions definitions_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.definitions
    ADD CONSTRAINT definitions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: definitions definitions_model_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.definitions
    ADD CONSTRAINT definitions_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.ai_models(id) ON DELETE RESTRICT;


--
-- Name: definitions definitions_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.definitions
    ADD CONSTRAINT definitions_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: run_targets run_targets_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.run_targets
    ADD CONSTRAINT run_targets_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.runs(id) ON DELETE CASCADE;


--
-- Name: runs runs_action_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.runs
    ADD CONSTRAINT runs_action_id_fkey FOREIGN KEY (action_id) REFERENCES public.actions(id) ON DELETE SET NULL;


--
-- Name: runs runs_actor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.runs
    ADD CONSTRAINT runs_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: runs runs_approved_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.runs
    ADD CONSTRAINT runs_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: runs runs_definition_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.runs
    ADD CONSTRAINT runs_definition_id_fkey FOREIGN KEY (definition_id) REFERENCES public.definitions(id) ON DELETE CASCADE;


--
-- Name: secrets secrets_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.secrets
    ADD CONSTRAINT secrets_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: tool_calls tool_calls_actor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_calls
    ADD CONSTRAINT tool_calls_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: tool_calls tool_calls_definition_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_calls
    ADD CONSTRAINT tool_calls_definition_id_fkey FOREIGN KEY (definition_id) REFERENCES public.definitions(id) ON DELETE SET NULL;


--
-- Name: tool_calls tool_calls_model_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_calls
    ADD CONSTRAINT tool_calls_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.ai_models(id) ON DELETE SET NULL;


--
-- Name: tool_calls tool_calls_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tool_calls
    ADD CONSTRAINT tool_calls_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.runs(id) ON DELETE SET NULL;


--
-- Name: user_invitations user_invitations_invited_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_invitations
    ADD CONSTRAINT user_invitations_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: user_invitations user_invitations_team_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_invitations
    ADD CONSTRAINT user_invitations_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id) ON DELETE SET NULL;


--
-- Name: users users_team_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id) ON DELETE SET NULL;


--
-- PostgreSQL database dump complete
--

\unrestrict rgjCT1JWfV2zMw4aCrJeMWMKpKsPQFXq4055DpFQeOxlw7TXkOPu624cXh35gBu

